### ISSUE TITLE
Keyboard shortcut for search

### ISSUE THREAD

**Issue by ash-jc-allen** [ash-jc-allen/find-a-pr#120]
I think it'd be nice to be able to press the `/` key on the keyboard to be able to autofocus on the search bar.

**Comment by ShaungBhone** [comment]
I can't install my local machine b/c of your bugsnag giving me 503 error even though I established bugsnag API key. [here](https://laracasts.com/discuss/channels/laravel/unable-to-create-configured-logger) I found the solution and it still does not work.

**Comment by ash-jc-allen** [comment]
Hey @ShaungBhone! It's likely that you're hitting the 503 error from hitting the GitHub rate limit?

Could you maybe share a screenshot of the error that you're getting? Thanks 😄

**Comment by ShaungBhone** [comment]
`[2022-08-12 15:24:23] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)
[stacktrace]
#0 /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(132): Illuminate\\Log\\LogManager->resolve()
#1 /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(119): Illuminate\\Log\\LogManager->get()
#2 /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(108): Illuminate\\Log\\LogManager->driver()`

**Comment by ash-jc-allen** [comment]
Could you please tell me what you have for these three fields in your `.env` file? 🙂

```
LOG_CHANNEL=
LOG_DEPRECATIONS_CHANNEL=
LOG_LEVEL=
```

**Comment by ShaungBhone** [comment]
I just copy from your env.example. Here is my .env
`LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug`

**Comment by ash-jc-allen** [comment]
Hmm okay, that's a weird one so I'll take a look into this. Just so that we can keep all of this info in an issue specific to this problem, could you please open up a new issue? In that issue, could you please let me know what the output of `sail php artisan about` gives you 🙂

**Comment by jeroen-hso** [comment]
`laravel.EMERGENCY: Unable to create configured logger. Using emergency logger`
is related to this setting

```
.env
LOG_DEPRECATIONS_CHANNEL=null
```

When I remove this entry the logger error is gone.

**Comment by jeroen-hso** [comment]
Regarding 503 error. To solve this, I changed in .env 

`DB_HOST=127.0.0.1`
to
`DB_HOST=mysql`

and migrated the database

`sail artisan migrate`

Last issue was the url vite public/hot file:
`http://0.0.0.0:5173`
to
`http://localhost:5173`

**Comment by ShaungBhone** [comment]
@jeroen-hso [here](https://github.com/ash-jc-allen/find-a-pr/issues/127#event-7182754949).

**Comment by jeroen-hso** [comment]
@ShaungBhone thanks! Yes I added github use and token as well. Didn't know that this solved the 503 error. I had several issues on startup. I will create separate issues and cleanup this issue.

**Comment by ash-jc-allen** [comment]
Hey @jeroen-hso, can we please keep the discussion regarding the 503 issue in this issue: https://github.com/ash-jc-allen/find-a-pr/issues/127. It just makes it easier for me to keep on top of issue tracking 😄

**Comment by jeroen-hso** [comment]
@ash-jc-allen sorry, cleanup my comments in this thread and created two separate issues: https://github.com/ash-jc-allen/find-a-pr/issues/130 + https://github.com/ash-jc-allen/find-a-pr/issues/131 (with PR https://github.com/ash-jc-allen/find-a-pr/pull/132)
