### ISSUE TITLE
When clone and install findapr at local machine, got 503 error.

### ISSUE THREAD

**Issue by ShaungBhone** [ash-jc-allen/find-a-pr#127]
When I install findapr, I got 503 error.  I think that comes from [bugsnag](https://www.bugsnag.com/), so I established [bugsnag](https://www.bugsnag.com/) API key. [here](https://laracasts.com/discuss/channels/laravel/unable-to-create-configured-logger) I found the solution and it still does not work.
```
[2022-08-12 15:24:23] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207) [stacktrace] #0 /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(132): Illuminate\\Log\\LogManager->resolve() #1 /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(119): Illuminate\\Log\\LogManager->get() #2 /home/shaungbhone/Desktop/find-a-pr/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(108): Illuminate\\Log\\LogManager->driver()
```
**Environment** ....................................................................................................................  
  Application Name ....................................................................................................... Laravel  
  Laravel Version ......................................................................................................... 9.24.0  
  PHP Version .............................................................................................................. 8.1.0  
  Composer Version ........................................................................................................ 2.1.14  
  Environment .............................................................................................................. local  
  Debug Mode ............................................................................................................. ENABLED  
  URL .................................................................................................................. localhost  
  Maintenance Mode ........................................................................................................... OFF  

  **Cache** ..........................................................................................................................  
  Config .............................................................................................................. NOT CACHED  
  Events .............................................................................................................. NOT CACHED  
  Routes .............................................................................................................. NOT CACHED  
  Views ................................................................................................................... CACHED  

  **Drivers** ........................................................................................................................  
  Broadcasting ............................................................................................................... log  
  Cache ..................................................................................................................... file  
  Database ................................................................................................................. mysql  
  Logs ................................................................................................... stack / single, bugsnag  
  Mail ...................................................................................................................... smtp  
  Queue ..................................................................................................................... sync  
  Session ................................................................................................................... file

**Comment by rubenvanerk** [comment]
Can you try to set the github token? You can create one here: https://github.com/settings/tokens

Then in your .env set these 2 values:
```
GITHUB_USERNAME=
GITHUB_TOKEN=
```

**Comment by ShaungBhone** [comment]
It's working now. Thank you. Need to update README.md.

**Comment by ash-jc-allen** [comment]
@ShaungBhone From what I can see here there are 2 different issues being described here:

The first issue is the 503 error that you were getting from hitting the GitHub API rate limit. Without using the GitHub credentials in the `.env` file, I think you're rate limited to around 50 API calls per hour (or something around that). But by adding your credentials, you rate limit is increased to 5000 API calls per hour (or something around that). Due to the fact that there are 688 repos being crawled at the moment, this means that you'll always need to use credentials when making the API requests. I'll get the documentation updated to mention this. @rubenvanerk Based on this do you think it's worth us removing the public API calls completely now, seeing as they'll pretty much never work anymore?

The second issue is the error regarding the `deprecations` log channel. It looks like this is also a small issue on the production site as well and it's being recorded in the site logs. I'll do some investigation into this to find a fix for it 😄
