### ISSUE TITLE
Laravel.log emergency logger error

### ISSUE THREAD

**Issue by jeroen-hso** [ash-jc-allen/find-a-pr#130]
public/logs/laravel.log
`laravel.EMERGENCY: Unable to create configured logger. Using emergency logger`

Solution:
remove in .env
`LOG_DEPRECATIONS_CHANNEL=null`

Should this be updated in .env.example ?

**Comment by ash-jc-allen** [comment]
I've just pushed a quick change that's updated the field to be `stack` in the `.env.example.` Hopefully this should all be working now for new installs 🙂

**Comment by ash-jc-allen** [comment]
I'm just leaving this here for reference. It looked like the issue was being caused by a slight bug in Laravel, but it seems to be fixed now: https://github.com/laravel/laravel/pull/5974 🙂
