### ISSUE TITLE
Issue labels are sometimes displayed without padding

### ISSUE THREAD

**Issue by rubenvanerk** [ash-jc-allen/find-a-pr#144]
![image](https://user-images.githubusercontent.com/20305359/192718688-77119782-ec02-4d5e-896c-2c9e9c739df6.png)

Using Firefox.

**Comment by ash-jc-allen** [comment]
Oooh good spot, I hadn't noticed that 🙂

**Comment by ShaungBhone** [comment]
I can't push to my checkout branch. Permission denied.
