### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ahangarha** [ash-jc-allen/find-a-pr#25]
Interesting project!
I had the same idea but not for specific technology. I wanted to make it based on type of issues. I think both can be combined!

Anyway, I wanted to ask about license of this project. There is no license in the repo. The license section in the README also talks about Laravel license. May you please make it clear that if this project is a Free/Libre and Open Source software?

Thanks

**Comment by ash-jc-allen** [comment]
Hey @ahangarha!

I've not quite got around to updating the documentation sorry or choosing a license. I'm probably leaning towards the MIT or GPLv3 license, but haven't quite decided yet. I'll hopefully get around to choosing on in the next few days 😄

**Comment by ahangarha** [comment]
If it be APLG, it would be awesome. But even MIT is better than being proprietary. :+1:

**Comment by rubenvanerk** [comment]
Looks like this is fixed by https://github.com/ash-jc-allen/find-a-pr/commit/0c0add0c01fdbee473564e4b53a109ec360ceaf6

**Comment by ash-jc-allen** [comment]
Ooops! Good spot, I forgot to close this issue. Thanks for picking up on it @rubenvanerk 🙂

**Comment by ahangarha** [comment]
Thanks
