### ISSUE TITLE
Use Laravel Mix

### ISSUE THREAD

**Issue by ash-jc-allen** [ash-jc-allen/find-a-pr#3]
To get an MVP together quickly, I didn't set up Laravel Mix properly.

So, the image fields are directly in the `resources` folder. It would be nicer to have these in the `resources` and they could be copied over during the deployment/build process.

The app is also currently using Tailwind via the CDN. It would be nice to be using Tailwind via NPM instead so that we can purge the CSS during the build process.

**Comment by ordago** [comment]
Have you considered Vite as an alternative to Laravel Mix?

https://vitejs.dev

https://2021.stateofjs.com/en-US/libraries/build-tools/#build_tools_experience_ranking

**Comment by ash-jc-allen** [comment]
Hey @ordago! I'd definitely be open to accepting a PR for using Vite instead of Mix.

I've heard good things about it but not actually used it myself, so I probably wouldn't be the best person to review any additions. I'm sure I'll be able to find someone to give it a review though so we can start using it 😄

**Comment by ordago** [comment]
Hey @ash-jc-allen, the PR I did is kind of stale now. If you want to proceed with it I kind put the code up to date.
