### ISSUE TITLE
Tailwind linting

### ISSUE THREAD

**Issue by aliwesome** [ash-jc-allen/find-a-pr#71]
It would be better to have all Tailwind class names sorted in same and correct way, a linter would solve this problem.
[InteliSense](https://tailwindcss.com/docs/editor-setup#intelli-sense-for-vs-code) which was mentioned by core team in documentation would handle this.
It also helps for code readability and make contribution more easier.

**Comment by ash-jc-allen** [comment]
I'm going to close this for the time being. But if anyone manages to figure out an automated way of linting/sorting the Tailwind classes in the Blade files, I'll be happy to consider a PR for it 😄
