### ISSUE TITLE
Add PWA functionality

### ISSUE THREAD

**Issue by ash-jc-allen** [ash-jc-allen/find-a-pr#98]
Now that the site has support for being used on a mobile, I think it'd be really cool to take it a step further and add PWA functionality.

This could allow users to add the site as a PWA to their phones and PCs so that they can quickly jump in and check for open issues.

Of course, this isn't going to serve a huge amount of purpose, but could be a pretty good chance to experiment with some cool features.

**Comment by aliwesome** [comment]
@ash-jc-allen take a look at this [package](https://github.com/silviolleite/laravel-pwa), because this website is just one page, I guess there is no need for internal navigation.

**Comment by ash-jc-allen** [comment]
Hey @aliwesome! Thanks for the suggestion on the package. I've used that package before and it seemed to work pretty well, so I agree, that'd probably be a nice option to go with 😄

**Comment by GurpreetkaitCode** [comment]
It sounds great, I really like this idea. But the thing is that, What is reason behind this?

**Comment by ash-jc-allen** [comment]
Hey @GurpreetkaitCode! There isn't really a reason behind it. It's just a chance for us to contribute to a project and experiment with different features for a bit of fun 😄

**Comment by GurpreetkaitCode** [comment]
Yes🚀, Thanks got it. **😁**

**Comment by ash-jc-allen** [comment]
This has been merged and appears to be working now! 😄
